### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by K2333IWI** [ForestsKing/D3R#1]
您好，请问：
def getData(path='./dataset/', dataset='SWaT', period=1440, train_rate=0.8):
    init_data = np.load(path + '/'+dataset + '/' + dataset + '_train_data.npy')
    init_time = getTimeEmbedding(np.load(path + dataset + '/' + dataset + '_train_time.npy'))

    test_data = np.load(path + dataset + '/' + dataset + '_test_data.npy')
    test_time = getTimeEmbedding(np.load(path + dataset + '/' + dataset + '_test_time.npy'))
    test_label = np.load(path + dataset + '/' + dataset + '_test_label.npy')
在您所给的数据集链接中文件后缀data.npy和date.npy。请问time.npy是不是就是date.npy呢？

**Comment by ForestsKing** [comment]
是的
