### ISSUE TITLE
关于该模型复现参数的设置

### ISSUE THREAD

**Issue by mufiye** [ForestsKing/D3R#10]
作者您好，很感觉您能提供这么精彩的模型，我最近在学习时序异常检测，在复现该模型的时候发现在PSM和SWAT上的结果与论文描述差了5-10个点，不过在SMD数据集上结果十分接近，请问是PSM和SWAT的模型参数设置有所不同嘛？

**Comment by XiaoBuL** [comment]
I have also found this issue where the results have decreased by 5-10 points. Do you know the reasons for this decline?

**Comment by mufiye** [comment]
我发现是我改写的时候写错了损失函数，实际效果没有差太多，如果你差很多可能要检查一下代码，依赖包版本之类的

GreatLuis ***@***.***>于2025年1月15日 周三16:27写道：

**Comment by XiaoBuL** [comment]
我就是没有动他原来的代码，直接跑了，请问您pytorch版本是多少呀 依赖包的情况
---- 回复的原邮件 ----
***@***.***>发送日期2025年01月15日 18:38 ***@***.***> ***@***.***>,
***@***.***>主题Re: [ForestsKing/D3R] 关于该模型复现参数的设置 (Issue #10)
我发现是我改写的时候写错了损失函数，实际效果没有差太多，如果你差很多可能要检查一下代码，依赖包版本之类的 
GreatLuis ***@***.***>于2025年1月15日 周三16:27写道：
