### ISSUE TITLE
About threshold

### ISSUE THREAD

**Issue by jin210625** [ForestsKing/D3R#3]
你好，我刚开始研究时间序列的异常检测，我发现你代码里面的 threshold 是通过 SPOT 类计算得到的，这个类的计算有些复杂且缺乏注释和参考资料。请问您能解释一下这个类或者提供一些参考资料吗？

**Comment by ForestsKing** [comment]
论文：【KDD 2017】Anomaly detection in streams with extreme value theory
代码：https://github.com/limjcst/ads-evt
