### ISSUE TITLE
Why the results obtained are inconsistent

### ISSUE THREAD

**Issue by qupemg** [ForestsKing/D3R#4]
Why the results obtained are inconsistent

When using the evaluate function in the code, the result is as follows:
p:0.3486 R:0.9993 F1:0.4920 
When tested with sklearn's classification_report function, the result is:
PRF1 : 0
The above results were tested on our own dataset

**Comment by ForestsKing** [comment]
We are not using standard metrics that are suitable for discrete samples, but metrics that are more suitable for continuous time series:_Local Evaluation of Time Series Anomaly Detection Algorithms_
