### ISSUE TITLE
Why only use the last time step of each window to find the threshold?

### ISSUE THREAD

**Issue by hwanyu112** [ForestsKing/D3R#5]
你好，感谢提供如此杰出且创新的工作！

在阅读`exp\exp.py`中的`test` 部分代码时对这里有一些困惑：
```          
init_src, init_rec = [], []
for (batch_data, batch_time, batch_stable, batch_label) in tqdm(self.init_loader):
    _, _, recon = self._process_one_batch(batch_data, batch_time, batch_stable, train=False)
    init_src.append(batch_data.detach().cpu().numpy()[:, -1, :])
    init_rec.append(recon.detach().cpu().numpy()[:, -1, :])

test_label, test_src, test_rec = [], [], []
for (batch_data, batch_time, batch_stable, batch_label) in tqdm(self.test_loader):
    _, _, recon = self._process_one_batch(batch_data, batch_time, batch_stable, train=False)
    test_label.append(batch_label.detach().cpu().numpy()[:, -1, :])
    test_src.append(batch_data.detach().cpu().numpy()[:, -1, :])
    test_rec.append(recon.detach().cpu().numpy()[:, -1, :])
```
为什么只用每个window的最后一步来计算threshold呢？
期待得到你的解答，谢谢！

**Comment by ForestsKing** [comment]
Due to the overlapping time windows, taking the last timestamp is to ensure the real-time performance of online detection. You can also take the middle timestamp or the average of all timestamps according to your needs, or other options, all of which are acceptable.

**Comment by ForestsKing** [comment]
Due to the overlapping time windows, taking the last timestamp is to ensure the real-time performance of online detection. You can also take the middle timestamp or the average of all timestamps according to your needs, or other options, all of which are acceptable.
