### ISSUE TITLE
关于PSM和SWaT数据集复现结果的问题

### ISSUE THREAD

**Issue by Liubo-imut** [ForestsKing/D3R#6]
作者您好：
        我按照您发布的代码和数据集进行了PSM、SMD和SWaT的复现实验，现在得到SMD的实验结果与您论文中发布的结果相当，但是PSM和SWaT数据集的复现实验结果分别比论文中低了5.7%和10%。请问您在进行这两个数据集的实验中是否调整了部分实验参数？

**Comment by ShiyuFeng5** [comment]
> 作者您好： 我按照您发布的代码和数据集进行了PSM、SMD和SWaT的复现实验，现在得到SMD的实验结果与您论文中发布的结果相当，但是PSM和SWaT数据集的复现实验结果分别比论文中低了5.7%和10%。请问您在进行这两个数据集的实验中是否调整了部分实验参数？

您好，我从SWaT官网看到这个数据集有多个不同时期的数据集，请问是选其中一个做实验还是把所有都合起来做实验？

**Comment by shaieesss** [comment]
您好，部分基线例如anomaly transformer的性能原文已经达到0.97，想问一下您论文中性能为何如此低

**Comment by KYYOnull** [comment]
> > 作者您好： 我按照您发布的代码和数据集进行了PSM、SMD和SWaT的复现实验，现在得到SMD的实验结果与您论文中发布的结果相当，但是PSM和SWaT数据集的复现实验结果分别比论文中低了5.7%和10%。请问您在进行这两个数据集的实验中是否调整了部分实验参数？
> 
> 您好，我从SWaT官网看到这个数据集有多个不同时期的数据集，请问是选其中一个做实验还是把所有都合起来做实验？

不是哥们，肯定是复现作者给的数据集啊，你在说什么

**Comment by mufiye** [comment]
> 作者您好： 我按照您发布的代码和数据集进行了PSM、SMD和SWaT的复现实验，现在得到SMD的实验结果与您论文中发布的结果相当，但是PSM和SWaT数据集的复现实验结果分别比论文中低了5.7%和10%。请问您在进行这两个数据集的实验中是否调整了部分实验参数？

请问您后来有复现出来嘛，我在swat和psm数据集上复现也有较大的偏差

**Comment by shaieesss** [comment]
> > 作者您好： 我按照您发布的代码和数据集进行了PSM、SMD和SWaT的复现实验，现在得到SMD的实验结果与您论文中发布的结果相当，但是PSM和SWaT数据集的复现实验结果分别比论文中低了5.7%和10%。请问您在进行这两个数据集的实验中是否调整了部分实验参数？
> 
> 请问您后来有复现出来嘛，我在swat和psm数据集上复现也有较大的偏差

其实这种情况很普遍，一种解释就是电脑的差距，但从大多数论文的复现来看，结果不会有太大偏差，另一种解释就是为了发论文压低数值了，这也可以理解，也挺常见的
