### ISSUE TITLE
About the Threshold

### ISSUE THREAD

**Issue by Cloni418** [ForestsKing/D3R#7]
Hi, thanks for making the code public. I find that you use grid search to obtain the best SPOT parameters for each dataset and record the results with the highest F1 scores. I'm confused about the parameter search space for SPOT. Can you show it? I'm also confused if you have used the same parameter for each datasets.

**Comment by ForestsKing** [comment]
The q in SPOT is selected from [0.001, 0.005, 0.01, 0.05] to make the best detection result. The thresholds are different for each dataset due to the different ratio of anomalies in each dataset. Details can be found in script/run.sh.
