### ISSUE TITLE
命名错误

### ISSUE THREAD

**Issue by KYYOnull** [ForestsKing/D3R#8]
from model.dddr import DRDD 

DRDD 是个什么玩意

**Comment by ForestsKing** [comment]
I apologize for your confusion.DRDD was the initial name of our algorithm. It was later updated to DDDR in the paper, and the code was not completely updated.

**Comment by KYYOnull** [comment]
谢谢解答，您的工作对我目前的研究很重要，希望您上传的代码是最新的，避免复现中出现不必要的困惑，非常感谢您的及时回复
